branch-defaults:
  master:
    environment: f-eighteen-dev
global:
  application_name: f-eighteen
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: null
  profile: null
  sc: git
